[general]
fontname=Monospace 11
selchars=-A-Za-z0-9,./?%&#:_
scrollback=1000
bgcolor=#0d0d11
fgcolor=#e1e1e6
disallowbold=FALSE
boldbright=FALSE
tabpos=bottom
geometry_columns=100
geometry_rows=28
cursorblinks=TRUE
cursorunderline=FALSE
audiblebell=FALSE
tabclosebutton=TRUE
hidescrollbar=TRUE
hidemenubar=TRUE
hideclosebutton=FALSE
hideatabclose=TRUE
windowtitle=Terminal
tabbedwindow=FALSE
borderless=FALSE
color0=#121214
color1=#ff5555
color2=#50fa7b
color3=#f1fa8c
color4=#bd93f9
color5=#ff79c6
color6=#8be9fd
color7=#bfbfbf
color8=#504c67
color9=#ff6e6e
color10=#69ff94
color11=#ffffa5
color12=#d6acff
color13=#ff92d0
color14=#a4ffff
color15=#e6e6e6
